
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dudeappdev
    username: root
    password: nandhankrs
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  application:
    name: college-service

server:
  servlet:
    context-path: /college
  port: 8081